#!/usr/bin/python
import subprocess, logging
import sys, os, time

ROOT=os.path.dirname(os.path.abspath(__file__))


#defaults:
bots=2
image="dockemu"
server="192.168.8.66"
duration=60
delay=0

logging.basicConfig(filename='log/dockemu.log',level=logging.DEBUG,  format='%(asctime)s %(message)s', datefmt='%m/%d/%Y %I:%M:%S %p')


#intro banner
print "##############################################"
print "##############################################"
print "______ _____ _____  _   __ ________  ____   _ "
print "|  _  \  _  /  __ \| | / /|  ___|  \/  | | | |"
print "| | | | | | | /  \/| |/ / | |__ | .  . | | | |"
print "| | | | | | | |    |    \ |  __|| |\/| | | | |"
print "| |/ /\ \_/ / \__/\| |\  \| |___| |  | | |_| |"
print "|___/  \___/ \____/\_| \_/\____/\_|  |_/\___/ "
print ""
print "##############################################"
print "#########  WELCOME TO DOCKEMU V.1.0  #########"
print "##############################################"
print ""
print ""
try:
	bots = input('How many bots do you need? [defaults=%s]: '%bots)
	print
except KeyboardInterrupt:
	sys.exit(0)
except:
	print " bots not provided, using defaults (%s)"%bots
	print

#server to attack
try:
	aux = raw_input('Enter the IP of the server to attack? [defaults=%s]: '%server)
	if aux != "":
		server=aux
	print
except KeyboardInterrupt:
	sys.exit(0)
except:
	print  "server not provided, using defaults (%s)"%server
	print 

#duration of the experiment
try:
	duration = input('Enter the duration of the attack [defaults=%s s], -1=forever:  '%duration)
	print
except KeyboardInterrupt:
	sys.exit(0)
except:
	print  "duration not provided, using defaults (%s)"%duration
	print 


#delay between docker bots start
try:
	delay = input('Enter the delay between the start of each docker bot [defaults=%s s]: '%delay)
	print
except KeyboardInterrupt:
	sys.exit(0)
except:
	print  "delay not provided, using defaults (%s)"%delay
	print


print "STARTING DOCKEMU BOT-NET ...."
names=[]
for i in range(bots):
	logging.info("STARTING dockemu-%s"%i)
	cmd="docker run -d -v %s/log/:/var/log/dockemu/ --name  dockemu-%s -e 'server=%s' dockemu dockemu-%s &>/dev/null"%(ROOT,i,server,i)
	print cmd
	try:
		print
		p = subprocess.Popen(cmd , shell=True)
	except:
		print "CANNOT START dockemu-%s"%i
	time.sleep(delay)


failed=False
if duration > 0:
	print
	print "Waiting %ss to stop the attack (all docker botnet)"%duration
	time.sleep(duration)
	try:
		for i in range(bots):
			cmd="docker kill dockemu-%s && docker stop dockemu-%s  && docker rm dockemu-%s "%(i,i,i)
			logging.info("ENDING dockemu-%s"%i)
			print cmd
			try:
				p = subprocess.Popen(cmd , shell=True)
				print s
			except:
				failed=True
				print "failed to stop dockemu-%s!!"%i
	except:
		cmd="docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q)"
		p = subprocess.Popen(cmd , shell=True)

